//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShibaevaManagementCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buildings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Buildings()
        {
            this.Apartments = new HashSet<Apartments>();
        }
    
        public int BuildingID { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> ManagementStartDate { get; set; }
        public Nullable<int> Floors { get; set; }
        public Nullable<int> ApartmentsCount { get; set; }
        public Nullable<int> ConstructionYear { get; set; }
        public Nullable<decimal> TotalArea { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apartments> Apartments { get; set; }
    }
}
