//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShibaevaManagementCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debts
    {
        public int DebtID { get; set; }
        public int ApartmentID { get; set; }
        public System.DateTime DebtDate { get; set; }
        public Nullable<decimal> WaterDebt { get; set; }
        public Nullable<decimal> ElectricityDebt { get; set; }
    
        public virtual Apartments Apartments { get; set; }
    }
}
