//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShibaevaManagementCompany
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Runtime.Remoting.Contexts;

    public partial class ShibaevaManagementCompanyEntities : DbContext
    {
        public ShibaevaManagementCompanyEntities()
             : base("name=AdsServiceShibaevaEntities")
        {
        }
        private static ShibaevaManagementCompanyEntities _context;

        public static ShibaevaManagementCompanyEntities GetContext()
        {
            if (_context == null) _context = new ShibaevaManagementCompanyEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartments> Apartments { get; set; }
        public virtual DbSet<Buildings> Buildings { get; set; }
        public virtual DbSet<Debts> Debts { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<ServiceRequests> ServiceRequests { get; set; }
        public virtual DbSet<ы> sysdiagrams { get; set; }
    }
}
