//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShibaevaManagementCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequests
    {
        public int RequestID { get; set; }
        public int ApartmentID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
    
        public virtual Apartments Apartments { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
